<a href="https://colab.research.google.com/github/Anu-cse/CodeAlpha-Data-Analytics/blob/main/CodeAlpha_Task1_Web_Scraping.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# CodeAlpha Data Analytics Internship
# Task 1: Web Scraping
# Project: Book Data Web Scraping Using Python and BeautifulSoup

In [2]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

In [3]:
url = "https://books.toscrape.com/"
response = requests.get(url)
print("Status Code:", response.status_code)

Status Code: 200

In [4]:
soup = BeautifulSoup(response.text, "html.parser")
books = soup.find_all("article", class_="product_pod")
print("Number of books found:", len(books))

Number of books found: 20

In [5]:
data = []
for book in books:
    title = book.h3.a["title"]
    price = book.find("p", class_="price_color").text
    rating = book.p["class"][1]
    availability = book.find(
        "p", class_="instock availability"
    ).text.strip()
    data.append({
        "Title":title,
        "Price":price,
        "Rating":rating,
        "Availability":availability
    })
print("Books scraped successfully:", len(data))

Books scraped successfully: 20

In [6]:
df = pd.DataFrame(data)
display(df)

,Title,Price,Rating,Availability
0,A Light in the Attic,Â£51.77,Three,In stock
1,Tipping the Velvet,Â£53.74,One,In stock
2,Soumission,Â£50.10,One,In stock
3,Sharp Objects,Â£47.82,Four,In stock
4,Sapiens: A Brief History of Humankind,Â£54.23,Five,In stock
5,The Requiem Red,Â£22.65,One,In stock
6,The Dirty Little Secrets of Getting Your Dream...,Â£33.34,Four,In stock
7,The Coming Woman: A Novel Based on the Life of...,Â£17.93,Three,In stock
8,The Boys in the Boat: Nine Americans and Their...,Â£22.60,Four,In stock
9,The Black Maria,Â£52.15,One,In stock
10,"Starving Hearts (Triangular Trade Trilogy, #1)",Â£13.99,Two,In stock
11,Shakespeare's Sonnets,Â£20.66,Four,In stock
12,Set Me Free,Â£17.46,Five,In stock
13,Scott Pilgrim's Precious Little Life (Scott Pi...,Â£52.29,Five,In stock
14,Rip it Up and Start Again,Â£35.02,Five,In stock
15,Our Band Could Be Your Life: Scenes from the A...,Â£57.25,Three,In stock
16,Olio,Â£23.88,One,In stock
17,Mesaerion: The Best Science Fiction Stories 18...,Â£37.59,One,In stock
18,Libertarianism for Beginners,Â£51.33,Two,In stock
19,It's Only the Himalayas,Â£45.17,Two,In stock

In [7]:
df["Price"] = df["Price"].str.replace("Â£", "£", regex=False)
display(df.head())

                                   Title   Price Rating Availability
0                   A Light in the Attic  £51.77  Three     In stock
1                     Tipping the Velvet  £53.74    One     In stock
2                             Soumission  £50.10    One     In stock
3                          Sharp Objects  £47.82   Four     In stock
4  Sapiens: A Brief History of Humankind  £54.23   Five     In stock

In [8]:
print("Dataset Shape:", df.shape)
print("\nColumn Names:")
print(df.columns.tolist())
print("\nFirst 5 Records:")
display(df.head())

Dataset Shape: (20, 4)

Column Names:
['Title', 'Price', 'Rating', 'Availability']

First 5 Records:

                                   Title   Price Rating Availability
0                   A Light in the Attic  £51.77  Three     In stock
1                     Tipping the Velvet  £53.74    One     In stock
2                             Soumission  £50.10    One     In stock
3                          Sharp Objects  £47.82   Four     In stock
4  Sapiens: A Brief History of Humankind  £54.23   Five     In stock

In [9]:
print("Missing Values:")
print(df.isnull().sum())

Missing Values:
Title           0
Price           0
Rating          0
Availability    0
dtype: int64

In [10]:
print("Data Types:")
print(df.dtypes)

Data Types:
Title           object
Price           object
Rating          object
Availability    object
dtype: object

In [11]:
df.to_csv(
    "books_dataset.csv",
    index=False,
    encoding="utf-8-sig"
)
print("Dataset saved successfully!")

Dataset saved successfully!

In [12]:
print("Final Dataset")
print("=" * 50)
print("Total Records:", len(df))
print("Total Columns:", len(df.columns))
display(df)

Final Dataset
==================================================
Total Records: 20
Total Columns: 4

,Title,Price,Rating,Availability
0,A Light in the Attic,£51.77,Three,In stock
1,Tipping the Velvet,£53.74,One,In stock
2,Soumission,£50.10,One,In stock
3,Sharp Objects,£47.82,Four,In stock
4,Sapiens: A Brief History of Humankind,£54.23,Five,In stock
5,The Requiem Red,£22.65,One,In stock
6,The Dirty Little Secrets of Getting Your Dream...,£33.34,Four,In stock
7,The Coming Woman: A Novel Based on the Life of...,£17.93,Three,In stock
8,The Boys in the Boat: Nine Americans and Their...,£22.60,Four,In stock
9,The Black Maria,£52.15,One,In stock
10,"Starving Hearts (Triangular Trade Trilogy, #1)",£13.99,Two,In stock
11,Shakespeare's Sonnets,£20.66,Four,In stock
12,Set Me Free,£17.46,Five,In stock
13,Scott Pilgrim's Precious Little Life (Scott Pi...,£52.29,Five,In stock
14,Rip it Up and Start Again,£35.02,Five,In stock
15,Our Band Could Be Your Life: Scenes from the A...,£57.25,Three,In stock
16,Olio,£23.88,One,In stock
17,Mesaerion: The Best Science Fiction Stories 18...,£37.59,One,In stock
18,Libertarianism for Beginners,£51.33,Two,In stock
19,It's Only the Himalayas,£45.17,Two,In stock

## Objective

The objective of this project is to extract book information from a public website using Python and BeautifulSoup. The collected information is organized into a structured dataset containing book title, price, rating, and availability.

## Tools and Libraries Used

- Python
- Requests
- BeautifulSoup
- Pandas
- Google Colab

## Methodology

* Selected a publicly available website for web scraping.
* Sent a request to the website using the Requests library.
* Used BeautifulSoup to read and parse the HTML structure.
* Identified the required book information from the webpage.
* Extracted the title, price, rating, and availability of each book.
* Stored the extracted information in a Pandas DataFrame.
* Checked the dataset for missing values and data types.
* Saved the final dataset as a CSV file.

## Dataset Description

The dataset contains information collected from the first page of the Books to Scrape website.
The dataset includes the following columns:
- Title – Name of the book
- Price – Price of the book
- Rating – Rating given to the book
- Availability – Availability status of the book

Total records collected: 20
Total columns: 4

## Result

The web scraping process was successfully completed. A dataset containing 20 book records was extracted from the website and stored in a structured format.

The final dataset was also saved as `books_dataset.csv`.

## Conclusion

This project demonstrates how Python and BeautifulSoup can be used to collect structured information from a public webpage. The extracted data was cleaned, checked, organized using Pandas, and saved as a CSV dataset for further analysis.